=== enonic/xp/modules/core-api/src/main/resources/com/enonic/wem/api/xml/schema/model.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="content-type" type="contentType"/>
    <xs:element name="image-component" type="imageDescriptor"/>
    <xs:element name="layout-component" type="layoutDescriptor"/>
    <xs:element name="mixin" type="mixin"/>
    <xs:element name="module" type="module"/>
    <xs:element name="page-component" type="pageDescriptor"/>
    <xs:element name="part-component" type="partDescriptor"/>
    <xs:element name="relationship-type" type="relationshipType"/>
    <xs:complexType final="extension restriction" name="module">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="version" type="xs:string"/>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="url" type="xs:string"/>
            <xs:element minOccurs="0" name="vendor" type="vendor"/>
          <xs:element minOccurs="0" name="content" type="metaSteps"/>
            <xs:element minOccurs="0" name="config" type="form"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="vendor">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="url" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
  <xs:complexType final="extension restriction" name="metaSteps">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0"
                  name="meta-step" type="metaStep"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType final="extension restriction" name="metaStep">
    <xs:sequence/>
    <xs:attribute name="mixin" type="xs:string" use="required"/>
  </xs:complexType>
    <xs:complexType final="extension restriction" name="form">
        <xs:complexContent>
            <xs:extension base="formItems">
                <xs:sequence/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="formItems">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="input" type="input"/>
                <xs:element name="mixin-reference" type="mixinReference"/>
                <xs:element name="field-set" type="fieldSet"/>
                <xs:element name="form-item-set" type="formItemSet"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="input">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element minOccurs="0" name="label" type="xs:string"/>
                    <xs:element minOccurs="0" name="immutable" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="indexed" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="custom-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="help-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="validation-regexp" type="xs:string"/>
                    <xs:element minOccurs="0" name="occurrences" type="occurrence"/>
                    <xs:element minOccurs="0" name="config" type="xs:anyType"/>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="formItem">
        <xs:sequence/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="occurrence">
        <xs:sequence/>
        <xs:attribute name="minimum" type="xs:int" use="required"/>
        <xs:attribute name="maximum" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="mixinReference">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element name="reference" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="fieldSet">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element minOccurs="0" name="label" type="xs:string"/>
                    <xs:element minOccurs="0" name="items" type="formItems"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="formItemSet">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element minOccurs="0" name="label" type="xs:string"/>
                    <xs:element minOccurs="0" name="immutable" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="custom-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="help-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="occurrences" type="occurrence"/>
                    <xs:element minOccurs="0" name="items" type="formItems"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="contentType">
        <xs:sequence>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="content-display-name-script" type="xs:string"/>
            <xs:element minOccurs="0" name="super-type" type="xs:string"/>
            <xs:element minOccurs="0" name="is-abstract" type="xs:boolean"/>
            <xs:element minOccurs="0" name="is-final" type="xs:boolean"/>
            <xs:element minOccurs="0" name="is-built-in" type="xs:boolean"/>
            <xs:element minOccurs="0" name="allow-child-content" type="xs:boolean"/>
            <xs:element minOccurs="0" name="form" type="formItems"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="mixin">
        <xs:sequence>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="items" type="formItems"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="layoutDescriptor">
        <xs:sequence>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
            <xs:element minOccurs="0" name="regions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0"
                            name="region" type="regionDescriptor"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="regionDescriptor">
        <xs:sequence/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="pageDescriptor">
        <xs:sequence>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
            <xs:element minOccurs="0" name="regions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0"
                            name="region" type="regionDescriptor"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="partDescriptor">
        <xs:sequence>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="imageDescriptor">
        <xs:sequence>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType final="extension restriction" name="relationshipType">
        <xs:sequence>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="from-semantic" type="xs:string"/>
            <xs:element minOccurs="0" name="to-semantic" type="xs:string"/>
            <xs:element minOccurs="0" name="allowed-from-types">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0"
                            name="content-type" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="allowed-to-types">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0"
                            name="content-type" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== enonic/xp/modules/core-api/src/main/resources/com/enonic/wem/api/xml/examples/module.xml
<?xml version="1.0" encoding="UTF-8" ?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/model.xsd">

  <name>mymodule</name>
  <version>1.0.0</version>
  <display-name>My Test Module</display-name>

  <vendor>
    <name>Enonic</name>
    <url>http://www.enonic.com</url>
  </vendor>

  <content>
    <meta-step mixin="system:menu-item"/>
    <meta-step mixin="mymodule:my-meta-mixin"/>
  </content>

  <config>
    <mixin-reference name="test">
      <reference>mymodule-1.0.0:other</reference>
    </mixin-reference>
  </config>

</module>
