=== enonic/xp/modules/core-api/src/main/resources/META-INF/xsd/export.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"
           xmlns="urn:enonic:xp:export:1.0" targetNamespace="urn:enonic:xp:export:1.0"
           elementFormDefault="qualified">

  <xs:complexType name="node">
    <xs:all>
      <xs:element minOccurs="0" maxOccurs="1" name="permissions" type="permissions"/>
      <xs:element minOccurs="0" maxOccurs="1" name="id" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="childOrder" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="1" name="nodeType" type="xs:string"/>
      <xs:element name="data" type="propertyTree"/>
      <xs:element minOccurs="0" maxOccurs="1" name="indexConfigs" type="indexConfigs"/>
      <xs:element minOccurs="0" maxOccurs="1" name="timestamp" type="xs:string"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="propertyTree">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:choice>
        <xs:element name="localDateTime" type="localDateTimeProperty" nillable="true"/>
        <xs:element name="string" type="stringProperty" nillable="true"/>
        <xs:element name="double" type="doubleProperty" nillable="true"/>
        <xs:element name="long" type="longProperty" nillable="true"/>
        <xs:element name="geoPoint" type="geoPointProperty" nillable="true"/>
        <xs:element name="boolean" type="booleanProperty" nillable="true"/>
        <xs:element name="dateTime" type="dateTimeProperty" nillable="true"/>
        <xs:element name="localDate" type="dateProperty" nillable="true"/>
        <xs:element name="localTime" type="timeProperty" nillable="true"/>
        <xs:element name="binaryReference" type="binaryReferenceProperty" nillable="true"/>
        <xs:element name="reference" type="referenceProperty" nillable="true"/>
        <xs:element name="link" type="linkProperty" nillable="true"/>
        <xs:element name="htmlPart" type="htmlPartProperty" nillable="true"/>
        <xs:element name="xml" type="xmlProperty" nillable="true"/>
        <xs:element name="property-set" type="propertySet" nillable="true"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:attributeGroup name="property">
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:attributeGroup>

  <xs:complexType name="propertySet">
    <xs:complexContent>
      <xs:extension base="propertyTree">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="stringProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="geoPointProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="doubleProperty">
    <xs:simpleContent>
      <xs:extension base="xs:double">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="longProperty">
    <xs:simpleContent>
      <xs:extension base="xs:long">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="booleanProperty">
    <xs:simpleContent>
      <xs:extension base="xs:boolean">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dateTimeProperty">
    <xs:simpleContent>
      <xs:extension base="xs:dateTime">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dateProperty">
    <xs:simpleContent>
      <xs:extension base="xs:date">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="timeProperty">
    <xs:simpleContent>
      <xs:extension base="xs:time">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="binaryReferenceProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="htmlPartProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="xmlProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="linkProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="referenceProperty">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="localDateTimeProperty">
    <xs:simpleContent>
      <xs:extension base="xs:dateTime">
        <xs:attributeGroup ref="property"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="indexConfig">
    <xs:sequence>
      <xs:element name="decideByType" type="xs:boolean"/>
      <xs:element name="enabled" type="xs:boolean"/>
      <xs:element name="nGram" type="xs:boolean"/>
      <xs:element name="fulltext" type="xs:boolean"/>
      <xs:element name="includeInAllText" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="pathIndexConfig">
    <xs:sequence>
      <xs:element name="indexConfig" type="indexConfig"/>
      <xs:element name="path" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="indexConfigs">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="analyzer" type="xs:string"/>
      <xs:element minOccurs="1" maxOccurs="1" name="defaultConfig" type="indexConfig"/>
      <xs:element minOccurs="0" maxOccurs="1" name="pathIndexConfigs">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="pathIndexConfig" type="pathIndexConfig"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="permissions">
    <xs:sequence>
      <xs:element name="principal" maxOccurs="unbounded" minOccurs="0" type="principal">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="principal">
    <xs:sequence>
      <xs:element name="allow" type="accessRightList" maxOccurs="1" minOccurs="1"/>
      <xs:element name="deny" type="accessRightList" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="key" use="required"/>
  </xs:complexType>

  <xs:complexType name="accessRightList">
    <xs:sequence>
      <xs:element type="xs:string" name="value" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type" use="optional"/>
  </xs:complexType>

  <xs:element name="node" type="node"/>

</xs:schema>

=== enonic/xp/modules/core-export/src/main/xsd/examples/example.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:enonic:xp:export:1.0"
      xsi:schemaLocation="urn:enonic:xp:export:1.0 ../export.xsd">

  <childOrder>_manualordervalue DESC</childOrder>
  <nodeType>content</nodeType>
  <data>
    <string name="test">value</string>
    <double name="test">3232.23</double>
    <long name="test">1234567891011121314</long>
    <geoPoint name="test">large</geoPoint>
    <boolean name="myBoolean">true</boolean>
    <dateTime name="myInstant">2014-11-28T09:10:00Z</dateTime>
    <localDateTime name="myLDT">2014-11-28T09:10:00Z</localDateTime>
    <localDate name="myLocalDate">2014-11-28</localDate>
    <localTime name="myLocalDate">09:10:00</localTime>
    <reference name="myRef">1234567890</reference>
    <link name="myLink">/content/stuff/more/here</link>
    <binaryReference name="myfile">fish_recipe.pdf</binaryReference>
    <htmlPart name="myPart">
      <![CDATA[
        <h1>This is my title</h1>
        <h2>This is my subtitle</h2>
      ]]>
    </htmlPart>
    <xml name="myXml">
      <![CDATA[
       <property-set name="test">
          <property-set name="eee">
              <string name="test">value</string>
          </property-set>
       </property-set>
      ]]>
    </xml>
    <string name="test">value</string>
    <property-set name="test">
      <property-set name="eee">
        <string name="test">value</string>
      </property-set>
    </property-set>
  </data>
  <indexConfigs>
    <analyzer>myAnalyzer</analyzer>
    <defaultConfig>
      <decideByType>false</decideByType>
      <enabled>true</enabled>
      <nGram>true</nGram>
      <fulltext>true</fulltext>
      <includeInAllText>true</includeInAllText>
    </defaultConfig>
    <pathIndexConfigs>
      <pathIndexConfig>
        <indexConfig>
          <decideByType>true</decideByType>
          <enabled>true</enabled>
          <nGram>true</nGram>
          <fulltext>true</fulltext>
          <includeInAllText>true</includeInAllText>
        </indexConfig>
        <path>myProperty</path>
      </pathIndexConfig>
      <pathIndexConfig>
        <indexConfig>
          <decideByType>true</decideByType>
          <enabled>false</enabled>
          <nGram>false</nGram>
          <fulltext>true</fulltext>
          <includeInAllText>false</includeInAllText>
        </indexConfig>
        <path>myOtherProperty</path>
      </pathIndexConfig>
    </pathIndexConfigs>
  </indexConfigs>
</node>
